### ISSUE TITLE
Line is a stack of all data

### ISSUE THREAD

**Issue by alex-stout** [clearwater-labs/energyDashboard#100]
I'm still having a problem with it.

<img width="1632" alt="Screen Shot 2019-04-15 at 5 28 44 PM" src="https://user-images.githubusercontent.com/17804548/56169482-e8b51400-5fa3-11e9-95db-915b5ff37a68.png">

**Comment by BrandonPessman** [comment]
@alex-stout I will clone a new copy of the repo this week and compare the two to see what is going on.

**Comment by BrandonPessman** [comment]
Fixed by changing to Epoch Time
